# nginx/default.conf

upstream django_server {
    # 這裡的 web 是對應 docker-compose 裡的服務名稱，8000 是 Gunicorn 跑的埠號
    server web:8000;
}

server {
    listen 80;
    server_name localhost;

    # 1. 處理所有的靜態檔案 (CSS, JS)
    location /static/ {
        alias /app/staticfiles/;
    }

    # 2. 處理所有的媒體檔案 (使用者上傳的圖片)
    location /media/ {
        alias /app/media/;
    }

    # 3. 其他所有請求，都轉發給後端的 Django (Gunicorn) 處理
    location / {
        proxy_pass http://django_server;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }
}
